# Practice 2. NumPy & Pandas Foundations: NumPy arrays, Pandas indexi filtering, and initial EDA.

### Imports

In [2]:
import numpy as np
import numpy.random as npr
import pandas as pd

### Setting seed for random number generator

In [3]:
rng = npr.default_rng(seed=67)

## Task 1. NumPy

#### Random 2-d array of integers

In [4]:
arr = rng.integers(low=-10, high=10, size=(5, 5))

In [5]:
arr

array([[  5,  -2,   1,  -8,  -2],
       [  0,   2,  -5,   4,   1],
       [  3,  -2,   7,  -4,  -8],
       [ -3,  -2,  -9,  -7,   8],
       [  0,  -6,  -3, -10,   5]])

#### Shape, ndim, size, and dtype

In [6]:
arr.shape

(5, 5)

In [7]:
arr.ndim

2

In [8]:
arr.size

25

In [9]:
arr.dtype

dtype('int64')

#### Indexing and slicing

##### Basic indexing and slicing

In [10]:
arr

array([[  5,  -2,   1,  -8,  -2],
       [  0,   2,  -5,   4,   1],
       [  3,  -2,   7,  -4,  -8],
       [ -3,  -2,  -9,  -7,   8],
       [  0,  -6,  -3, -10,   5]])

In [11]:
arr[0]

array([ 5, -2,  1, -8, -2])

In [12]:
arr[0, 0]

np.int64(5)

In [13]:
arr[:]

array([[  5,  -2,   1,  -8,  -2],
       [  0,   2,  -5,   4,   1],
       [  3,  -2,   7,  -4,  -8],
       [ -3,  -2,  -9,  -7,   8],
       [  0,  -6,  -3, -10,   5]])

In [14]:
arr[0:2]

array([[ 5, -2,  1, -8, -2],
       [ 0,  2, -5,  4,  1]])

In [15]:
arr[:2]

array([[ 5, -2,  1, -8, -2],
       [ 0,  2, -5,  4,  1]])

In [16]:
arr[:2, 2:]

array([[ 1, -8, -2],
       [-5,  4,  1]])

In [17]:
arr[:, 0]

array([ 5,  0,  3, -3,  0])

##### Boolean indexing

Indexing using boolean arrays

In [18]:
arr

array([[  5,  -2,   1,  -8,  -2],
       [  0,   2,  -5,   4,   1],
       [  3,  -2,   7,  -4,  -8],
       [ -3,  -2,  -9,  -7,   8],
       [  0,  -6,  -3, -10,   5]])

In [19]:
arr_copy = arr.copy()

In [20]:
arr_copy > 0

array([[ True, False,  True, False, False],
       [False,  True, False,  True,  True],
       [ True, False,  True, False, False],
       [False, False, False, False,  True],
       [False, False, False, False,  True]])

In [21]:
arr_copy[arr_copy > 0]

array([5, 1, 2, 4, 1, 3, 7, 8, 5])

In [22]:
arr_copy[arr_copy < 0] = 0

In [23]:
arr_copy

array([[5, 0, 1, 0, 0],
       [0, 2, 0, 4, 1],
       [3, 0, 7, 0, 0],
       [0, 0, 0, 0, 8],
       [0, 0, 0, 0, 5]])

In [24]:
bool_arr = np.array([True, False, True, False, True])

In [25]:
arr_copy[bool_arr]

array([[5, 0, 1, 0, 0],
       [3, 0, 7, 0, 0],
       [0, 0, 0, 0, 5]])

##### Fancy indexing

Indexing using integer arrays

In [26]:
arr

array([[  5,  -2,   1,  -8,  -2],
       [  0,   2,  -5,   4,   1],
       [  3,  -2,   7,  -4,  -8],
       [ -3,  -2,  -9,  -7,   8],
       [  0,  -6,  -3, -10,   5]])

In [27]:
arr[[0, 2, 4]]

array([[  5,  -2,   1,  -8,  -2],
       [  3,  -2,   7,  -4,  -8],
       [  0,  -6,  -3, -10,   5]])

In [28]:
arr[[-1, -3, -5]]

array([[  0,  -6,  -3, -10,   5],
       [  3,  -2,   7,  -4,  -8],
       [  5,  -2,   1,  -8,  -2]])

In [29]:
arr[[0, 2, 4], [0, 2, 4]]

array([5, 7, 5])

In [30]:
arr[[0, 2, 4]][:, [0, 2, 4]]

array([[ 5,  1, -2],
       [ 3,  7, -8],
       [ 0, -3,  5]])

#### Basic array statistics

In [31]:
arr

array([[  5,  -2,   1,  -8,  -2],
       [  0,   2,  -5,   4,   1],
       [  3,  -2,   7,  -4,  -8],
       [ -3,  -2,  -9,  -7,   8],
       [  0,  -6,  -3, -10,   5]])

In [32]:
arr.T

array([[  5,   0,   3,  -3,   0],
       [ -2,   2,  -2,  -2,  -6],
       [  1,  -5,   7,  -9,  -3],
       [ -8,   4,  -4,  -7, -10],
       [ -2,   1,  -8,   8,   5]])

In [33]:
arr.swapaxes(0, 1)

array([[  5,   0,   3,  -3,   0],
       [ -2,   2,  -2,  -2,  -6],
       [  1,  -5,   7,  -9,  -3],
       [ -8,   4,  -4,  -7, -10],
       [ -2,   1,  -8,   8,   5]])

In [34]:
arr.T == arr.swapaxes(1, 0)

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [35]:
arr.mean()

np.float64(-1.4)

In [36]:
arr.mean(axis=0)

array([ 1. , -2. , -1.8, -5. ,  0.8])

In [37]:
arr.mean(axis=1)

array([-1.2,  0.4, -0.8, -2.6, -2.8])

In [38]:
arr.sum()

np.int64(-35)

In [39]:
arr.sum(axis=0)

array([  5, -10,  -9, -25,   4])

In [40]:
arr.sum(axis=1)

array([ -6,   2,  -4, -13, -14])

In [41]:
arr.cumsum()

array([  5,   3,   4,  -4,  -6,  -6,  -4,  -9,  -5,  -4,  -1,  -3,   4,
         0,  -8, -11, -13, -22, -29, -21, -21, -27, -30, -40, -35])

In [42]:
arr.cumprod()

array([   5,  -10,  -10,   80, -160,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0])

In [43]:
arr.std()

np.float64(4.955804677345546)

In [44]:
arr.var()

np.float64(24.56)

In [45]:
arr.argmin()

np.int64(23)

In [46]:
arr.min()

np.int64(-10)

In [47]:
arr.flatten()[arr.argmin()]

np.int64(-10)

##### Vectorized operations

In [48]:
np.square(arr)

array([[ 25,   4,   1,  64,   4],
       [  0,   4,  25,  16,   1],
       [  9,   4,  49,  16,  64],
       [  9,   4,  81,  49,  64],
       [  0,  36,   9, 100,  25]])

In [49]:
np.exp(arr)

array([[1.48413159e+02, 1.35335283e-01, 2.71828183e+00, 3.35462628e-04,
        1.35335283e-01],
       [1.00000000e+00, 7.38905610e+00, 6.73794700e-03, 5.45981500e+01,
        2.71828183e+00],
       [2.00855369e+01, 1.35335283e-01, 1.09663316e+03, 1.83156389e-02,
        3.35462628e-04],
       [4.97870684e-02, 1.35335283e-01, 1.23409804e-04, 9.11881966e-04,
        2.98095799e+03],
       [1.00000000e+00, 2.47875218e-03, 4.97870684e-02, 4.53999298e-05,
        1.48413159e+02]])

In [50]:
remainder, whole_part = np.modf(arr)

In [51]:
remainder, whole_part

(array([[ 0., -0.,  0., -0., -0.],
        [ 0.,  0., -0.,  0.,  0.],
        [ 0., -0.,  0., -0., -0.],
        [-0., -0., -0., -0.,  0.],
        [ 0., -0., -0., -0.,  0.]]),
 array([[  5.,  -2.,   1.,  -8.,  -2.],
        [  0.,   2.,  -5.,   4.,   1.],
        [  3.,  -2.,   7.,  -4.,  -8.],
        [ -3.,  -2.,  -9.,  -7.,   8.],
        [  0.,  -6.,  -3., -10.,   5.]]))

## Task 2. DataFrame

In [52]:
df = pd.read_csv("./archive/Titanic-Dataset.csv")

In [53]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

#### Basic information

In [54]:
df.size

10692

In [55]:
df.shape

(891, 12)

In [56]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

#### Basic descriptive information

In [57]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [58]:
df.iloc[0]

PassengerId                          1
Survived                             0
Pclass                               3
Name           Braund, Mr. Owen Harris
Sex                               male
Age                               22.0
SibSp                                1
Parch                                0
Ticket                       A/5 21171
Fare                              7.25
Cabin                              NaN
Embarked                             S
Name: 0, dtype: object

1. **PassengerId** - Passenger ID


2. **Survived** - Weather Survived or not: 0 = No, 1 = Yes


3. **Pclass** - Ticket class: 1 = 1st, 2 = 2nd, 3 = 3rd


4. **Name** - Name of the Passenger


5. **Sex** - Gender


6. **Age** - Age in Years


7. **SibSp** - No. of siblings / spouses aboard the Titanic


8. **Parch** - No. of parents / children aboard the Titanic


9. **Ticket** - Ticket number


10. **Fare** - Passenger fare

11. **Cabin** - Cabin number

12. **Embarked** - Port of Embarkation:C = Cherbourg, Q = Queenstown, S = Southampton

## Task 3. Indexing

In [59]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [60]:
df.iloc[0] # select by integer index starting from 0

PassengerId                          1
Survived                             0
Pclass                               3
Name           Braund, Mr. Owen Harris
Sex                               male
Age                               22.0
SibSp                                1
Parch                                0
Ticket                       A/5 21171
Fare                              7.25
Cabin                              NaN
Embarked                             S
Name: 0, dtype: object

In [61]:
df.loc[0] # select by index

PassengerId                          1
Survived                             0
Pclass                               3
Name           Braund, Mr. Owen Harris
Sex                               male
Age                               22.0
SibSp                                1
Parch                                0
Ticket                       A/5 21171
Fare                              7.25
Cabin                              NaN
Embarked                             S
Name: 0, dtype: object

In [62]:
df['PassengerId']

0        1
1        2
2        3
3        4
4        5
      ...
886    887
887    888
888    889
889    890
890    891
Name: PassengerId, Length: 891, dtype: int64

In [63]:
df[['Name', 'Sex', 'Survived']].head()

                                                Name     Sex  Survived
0                            Braund, Mr. Owen Harris    male         0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female         1
2                             Heikkinen, Miss. Laina  female         1
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female         1
4                           Allen, Mr. William Henry    male         0

In [64]:
df.iloc[0:4]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S

In [65]:
df.iloc[0:10:2]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S

In [66]:
df.iloc[0, [0, 3, 4]]

PassengerId                          1
Name           Braund, Mr. Owen Harris
Sex                               male
Name: 0, dtype: object

In [67]:
df.iloc[0, 0]

np.int64(1)

In [68]:
df_head_reindexed = df.head().reindex([4, 3, 2, 1, 0])

In [69]:
df_head_reindexed

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S

In [70]:
df_head_reindexed.iloc[0, 3]

'Allen, Mr. William Henry'

In [71]:
df_head_reindexed.loc[0, 'Name']

'Braund, Mr. Owen Harris'

## Task4. Filtering

#### Question 1: How many passengers were adults?

In [72]:
(df[df['Age'] >= 18].count()).iloc[0]

np.int64(601)

#### Question 2: How many passengers were embarked in Queenstown?

In [73]:
df[df['Embarked'] == 'Q'].count().iloc[0]

np.int64(77)

#### Question 3: How many woman passengers survived?

In [74]:
df[(df['Sex'] == 'female') & (df['Survived'] == 1)].count().iloc[0]

np.int64(233)

#### Question 4: Which passengers had fare higher than the median?

In [75]:
print(f"Median: {df['Fare'].median()}")
df[df['Fare'] > df['Fare'].median()]

Median: 14.4542

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

## Task 5. EDA

#### Missing values and duplicates

In [76]:
df_clear = df

In [77]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [78]:
df_clear['Age'] = df['Age'].fillna(df['Age'].median())

In [79]:
df_clear['Age'].isna().sum()

np.int64(0)

In [80]:
df_clear = df_clear.drop(columns=['Cabin'])

In [81]:
df_clear.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(4)
memory usage: 76.7 KB

In [82]:
df_clear = df_clear[df_clear['Embarked'].notna()]

In [83]:
df_clear.info()

<class 'pandas.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  889 non-null    int64
 1   Survived     889 non-null    int64
 2   Pclass       889 non-null    int64
 3   Name         889 non-null    str
 4   Sex          889 non-null    str
 5   Age          889 non-null    float64
 6   SibSp        889 non-null    int64
 7   Parch        889 non-null    int64
 8   Ticket       889 non-null    str
 9   Fare         889 non-null    float64
 10  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(4)
memory usage: 83.3 KB

In [84]:
df_clear.duplicated().sum()

np.int64(0)

#### Numerical values statistics

In [85]:
df_clear[['Age', 'SibSp', 'Parch', 'Fare']].describe()

              Age       SibSp       Parch        Fare
count  889.000000  889.000000  889.000000  889.000000
mean    29.315152    0.524184    0.382452   32.096681
std     12.984932    1.103705    0.806761   49.697504
min      0.420000    0.000000    0.000000    0.000000
25%     22.000000    0.000000    0.000000    7.895800
50%     28.000000    0.000000    0.000000   14.454200
75%     35.000000    1.000000    0.000000   31.000000
max     80.000000    8.000000    6.000000  512.329200

#### Categorical values statistics

In [86]:
categories = ['Survived', 'Pclass', 'Sex', 'Embarked']

for category in categories:
    df_clear[category] = df_clear[category].astype('category')

In [87]:
df_clear[categories].describe()

        Survived  Pclass   Sex Embarked
count        889     889   889      889
unique         2       3     2        3
top            0       3  male        S
freq         549     491   577      644

#### Relationships

In [88]:
df_clear[['Age', 'Fare', 'Pclass', 'Survived']].corr()

               Age      Fare    Pclass  Survived
Age       1.000000  0.093707 -0.336512 -0.069822
Fare      0.093707  1.000000 -0.548193  0.255290
Pclass   -0.336512 -0.548193  1.000000 -0.335549
Survived -0.069822  0.255290 -0.335549  1.000000

In [89]:
df_clear.groupby('Sex')['Survived'].value_counts()

Sex     Survived
female  1           231
        0            81
male    0           468
        1           109
Name: count, dtype: int64